apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a3ljzp9kk-go 
  janus-idp.io/tekton: a3ljzp9kk-go
  backstage.io/kubernetes-id: a3ljzp9kk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a3ljzp9kk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml