apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: a3ljzp9kk-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9dc640e8938fb4d279d0abfb60f709d69f9d04f4@sha256:4cf73fdb74f10e3e681a38d936d589a07f97921c9c0dc83306879514ea5d8c96
          name: container-image
